### ISSUE TITLE
CLI exits with ambiguous/incoherent flags

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaConch_SourceCode#138]
`mediaconch -v` is a correct command and gives the supposed information, but exits with an error flag.
`mediaconch -version` is a wrong command and gives an error message, but exits with a non-error flag.
`mediaconch --version` is also a correct command and gives the supposed information, but exits with an error flag.
<img width="628" alt="bildschirmfoto 2016-01-11 um 21 55 29" src="https://cloud.githubusercontent.com/assets/3246607/12246305/1a66f946-b8ae-11e5-8cb7-68928d803f2b.png">
(My prompt is green if non-error flag and red if error flag.)

**Comment by retokromer** [comment]
I *suggest* also to exit `mediaconch -h` with a non-error flag, because – even if the command is not parsing – there is no error at all here.

**Comment by tribouille** [comment]
The --version or -v or -h or --help or -ha or --help=advanced or ... should not be anymore an error.
(Since 4 days)
You have to use the latest snapshots or wait for the next release. (End of january)
https://mediaarea.net/MediaConch/downloads/snapshots.html

We will change the parsing to be more standard for the "-version".
Until now, we were accepting a mix between options and arguments...
Now, we will force to have the options before the args... separate (if needed) by --.

For instance,
mediaconch -version : wrong command
mediaconch --version : correct command
mediaconch -v : correct command
mediaconch -- -version : correct command, report invalid (if the file -version is not existing)
mediaconch file.mov -p PolicyFile.xsl: correct command, report invalid (if the files "-p" or "PolicyFile.xsl" are not existing)

And correct the error message when a file is not existing (issue https://github.com/MediaArea/MediaConch_SourceCode/issues/107).

**Comment by retokromer** [comment]
Thank you!

**Comment by tribouille** [comment]
FYI: Command line changes: https://github.com/MediaArea/MediaConch_SourceCode/pull/140

**Comment by tribouille** [comment]
Should be corrected in snapshots.

For the error message, will be solved with MediaInfoLib (with ticket #107).

**Comment by retokromer** [comment]
It is! Merci beaucoup, @tribouille!
