### ISSUE TITLE
GUI/WUI: UX: Move "create policy from report" to policy page

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch_SourceCode#357]
I'd like to see the "Create Policy from This Report" move out of Mediainfo and into the Policy page, maybe at the top. Users go to the Policy page first to try to do this but can't find it and don't think of it being in the Mediainfo reporting. "Create policy based on this file" is perhaps more accurate (from a user's perspective) even if less accurate from a technical perspective. 

(All of those are pretty "long" for a button -- will have to think through how to shorten that.) "Create Policy from Report"?

**Comment by tribouille** [comment]
It was there because we had to put it somewhere and to have a PoC of the feature :)

Right now, the WUI is not saving files parsed. If you analyze some files, come back to checker page, everything is not there. That's why, we put it in the checker page... And it only creates policy from a MI report.
I agree it will be more accurate in the Policy page, but not possible right now.

There are 4 reports (Implementation, Policy, MI, MT), so, "from Report" should be more precise (at least until Policy do not manager MT).

But, as always for labels, I let Jerome decide.

**Comment by ablwr** [comment]
Oh I see, I didn't know there was a technical restriction but now I understand. That makes sense. I told users that this was still "in beta." :)

**Comment by GuillaumeRoques** [comment]
Done in #501
