### ISSUE TITLE
Policies: test on extra/ErrorDetectionType always fail

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaConch_SourceCode#429]
If I have a Matroska file and/or a FFV1 stream and I would like to test extra/ErrorDetectionType with "Xpath: mi:MediaInfo/mi:track[@type='Video'][*]/mi:extra/ErrorDetectionType='Per slice'", it awlays fails (even if the value is there)

**Comment by dericed** [comment]
Understood, should be `mi:MediaInfo/mi:track[@type='Video'][*]/mi:extra/mi:ErrorDetectionType='Per slice'"`

**Comment by dericed** [comment]
This should be assigned back to me. The handling is better to manage in xsl.

**Comment by JeromeMartinez** [comment]
should we or should we not have "mi:" in front of "ErrorDetectionType"?

**Comment by dericed** [comment]
not. The xsl handles namespaces.

**Comment by JeromeMartinez** [comment]
I don't understand the coherence: the XML has sometimes mi: and sometimes not.
What is the principle?

**Comment by dericed** [comment]
Goal is that the policy does not include the namespace (`mi:`, `mt:`, `mmt:`), but the xsl processing adds this depending on the scope (which defaults to `mi:` if no scope value).

**Comment by JeromeMartinez** [comment]
ok, understood, nothing in the Policy XML, issue on transformation XSL only.

**Comment by dericed** [comment]
IMHO, the user should not worry about namespace, ie I prefer they select `Format` rather than `mi:Format` or `extra/ErrorCorrectionType` rather than `mi:extra/mi:ErrorCorrectionType`. The issue of this ticket was the xsl transformation converted `extra/ErrorCorrectionType` to `mi:extra/ErrorCorrectionType` when I should do (as it does now) `mi:extra/mi:ErrorCorrectionType`.
