### ISSUE TITLE
Feedback buildenv09 20161201 (Ubuntu x86a64)

### ISSUE THREAD

**Issue by beyo-ra** [MediaArea/MediaConch_SourceCode#493]
Build tools and CLI/GUI dependencies
**Logs attached**
[buildenv09_u16v04x86a64_desktop.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/669853/buildenv09_u16v04x86a64_desktop.txt)
[buildenv09_u16v04x86a64_netinstall.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/669854/buildenv09_u16v04x86a64_netinstall.txt)
[buildenv09_u16v04x86a64_netinstall+ustdsut.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/669855/buildenv09_u16v04x86a64_netinstall.ustdsut.txt)

**Ubuntu 16.04 x86_64 netinstall**
- Without "standard system utilities"
- VirtualBox disabled Network Adapter
- Copy unziped files from USB to home directory

$ sudo dpkg -i * > ~/buildenv09_u16v04x86a64_netinstall.txt > 2>&1
- Failed
- Reset VirtualBox image and activate Network Adapter
- sudo apt-get update
- sudo apt-get install ubuntu-standard
$ sudo dpkg -i * > ~/buildenv09_u16v04x86a64_netinstall+ustdsut.txt > 2>&1
- failed

**Ubuntu 16.04 x86_64 desktop**
- Disabled Internet connection
- Disabled Download updates while installing Ubuntu
- Disabled Install third-party software for graphics and Wi-Fi hardware, Flash, MP3 and other media.

$ sudo dpkg -i * > ~/buildenv09_u16v04x86a64_desktop.txt > 2>&1

_Errors encountered while processing:_
 libdrm-dev:amd64
 libgl1-mesa-dev:amd64
 libglu1-mesa-dev:amd64
 libqt4-opengl-dev
 libxml2-dev:amd64
 libxslt1-dev:amd64
 mesa-common-dev:amd64

The subsequent compiling of sources was however successful
_MediaConch Implementation_
$ ./CLI_compile.sh
$ ./Server_compile.sh
$ ./GUI_compile.sh

_MediaConch Policy_
$ ./CLI_compile.sh
$ ./Server_compile.sh
$ ./GUI_compile.sh

**Comment by JeromeMartinez** [comment]
Error messages for desktop version: looks like similar to [this issue](https://github.com/MediaArea/MediaConch_SourceCode/issues/492) : we provide build environment for Ubuntu 16.04, not for 16.04.1 and the system prevents us from installing old versions. We could provide a development environment without error for 16.04.1 on request.

Netinstall: we tested on "Ubuntu 16.04 x86_64 desktop" minimal install, is Ubuntu 16.04 x86_64 "Ubuntu 16.04 x86_64 netinstall" requested? the PREFORMA docs specify "Ubuntu minimal" without specifying "netinstall" and we are using the most classical flavor of Ubuntu, anyway we could provide the missing files from the netinstall too.

**Comment by beyo-ra** [comment]
The intention is to provide helpful feedback for future reference. This is neither a request nor a formal reply to the CDP (that should be relayed through the usual channels I would assume).
**Re 16.04.1LTS**
That was the version available on Ubuntu when I downloaded the image.
- https://www.ubuntu.com/download/desktop

**Re netinstall**
I tested netinstall to see the extend of dependencies needed. Given the fact that netinstall requires an Internet connection it seems contradictory to require an offline setup ;)

**Comment by JeromeMartinez** [comment]
> This is neither a request nor a formal reply to the CDP

If it is blocking the acceptance, comments about that on the tracker before being in the usual channels would be appreciated so we can change it without waiting for the next round.

> That was the version available on Ubuntu when I downloaded the image.

Issue is that our delivery is done at a moment, and the page you are linking is dynamic and can change between the moment we prepare the delivery and the moment you test it, not speaking of the moment we have our build.
You can download 16.04 version at http://releases.ubuntu.com/16.04/ (both 16.04 and 16.04.1 are there)
But as you saw, main "issue" is that you already have the packets (younger version) and this does not prevent MediaConch compilation (Ubuntu takes care to keep the binary and source compatibility).

> I tested netinstall to see the extend of dependencies needed.

Mostly the Ubuntu UI, as it is not installed with the network install. It is not mandatory by MediaConch if you want to use the CLI or server version. Someone wanting to use MediaConch GUI would install the Ubuntu UI, from my point of view.

***

Can you confirm that this is for future reference and not something blocking the CDP acceptance?

**Comment by JeromeMartinez** [comment]
>  I expected the buildenv to be installed but only for compiling the CLI_compile.sh.

We did not understand the buildenv as for CLI only, so we delivered a buildenv fitting both CLI and GUI needs. Anyway, it would be doable to have a buildenv only for CLI (and/or for the "netinstall" and/or for 16.04.1 or any other version), it is a matter of agreeing about the exact content of the package.

> This is the result from my compilation on Ubuntu. 

Thanks for the confirmation

> I would have thought creating a package for the build environment that could be deployed on any/most non-specific Linux distro would have been preferable, no? Would that have been to complicated for C++?

This is different approach about compiling chains and resulting binaries (including their dependencies), I am not willing to go in another endless fight Java vs C/C++ (or language requesting a Virtual Machine in order to run and with a big default library, vs native code without a big default library and more tied to the libraries provided by the distro), they have both their pros and cons and both still exist for good reasons, just please note that you can do [`sudo apt-get install mediaconch`](http://packages.ubuntu.com/xenial/mediaconch) just after having installed Ubuntu and still without Internet connection because the Debian/Ubuntu maintainers considered our method for delivering development environment and source code as compatible with their standards and viable at long term (same for [Homebrew maintainers who support MediaConch](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mediaconch.rb), Homebrew being a [packet manager for Mac](http://brew.sh/)).
