### ISSUE TITLE
Issue with options and usage of "~" home shortcut

### ISSUE THREAD

**Issue by art1pirat** [MediaArea/MediaConch_SourceCode#566]
Hi,

i tried to call mediaconch cli with:

mediaconch --Policy=~/git/mediaconch-profile/SLUB_mediaconch_policy_retrodigitized_film35mm.xml  -fh test35mm.mkv > testreport35mm.html

the resulting file testreport35mm.html does not holds results from the given policy but with the default standard policy, if "--Policy" option was not used
The result contains "MediaConch EBML Implementation Checker". Also a diff between this call and the call without "--Policy" option displays only differences in <input id="$FOO" ..>, where $FOO is different.

If you select the policy in mediaconch-gui, all is working as expected.

**Comment by art1pirat** [comment]
The reason for this behaviour is the "~/" in the beginning of the file-name, if replaced with absolute path, everything works as expected

**Comment by JeromeMartinez** [comment]
"~" is expected to be expanded by the shell itself, I guess the issue is the "=" before this character and the shell does not expand "~".
` -p ~/git/mediaconch-profile/SLUB_mediaconch_policy_retrodigitized_film35mm.xml` should work (not tested, I have no Linux right now) because "~" should be correctly detected by the shell, and it is a synonym.

I am not sure about what we should do here, as it should be something done at the shell level. @tribouille ideas?

**Comment by tribouille** [comment]
It works with the -p ~/policy.xml

The shell is interpreting string with only a path on it.
With the "--policy=", it cannot interpret it.

On linux, we can use glob to interpret it.
(http://man7.org/linux/man-pages/man3/glob.3.html)
On other platform, I don't know...

**Comment by JeromeMartinez** [comment]
Looks like it works also on Mac ([Expanding Tilde-based paths](https://developer.apple.com/library/content/qa/qa1549/_index.html)). Not applicable for Windows.
So let's go with glob.h (where it works).

**Comment by JeromeMartinez** [comment]
Available in [snapshots](https://mediaarea.net/download/snapshots/binary/mediaconch/) or next version.
