### ISSUE TITLE
Mediaconch returns empty as actual whereas MediaInfo gives value

### ISSUE THREAD

**Issue by XMegamanX** [MediaArea/MediaConch_SourceCode#653]
Hello !
I use MediaInfo Command Line, MediaInfoLib - v18.05 and MediaConch Command Line Interface 18.03.2. 

MediaInfo returns a value for the  element 'GOP, Open/Closed' - ': Closed' but if I add this rule to MediaConch 
```
<rule name="Video/Gop" value="Gop_OpenClosed" tracktype="Video" occurrence="*" operator="=">Closed</rule>
```
it returns 
```
<rule name="Video/Gop" value="Gop_OpenClosed" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Gop_OpenClosed='Closed'" actual="" outcome="fail"/>
```

Why does 'Gop_OpenClosed' for 'Video' track not appear in mediaconch ? Am I miswrite something ?

Thanks for the help.

**Comment by JeromeMartinez** [comment]
The rule is fine.

Issue is that MediaInfo library is configured for faster analysis in MediaConch by default, which removes the analysis of GOP open/closed (I check several GOP in order to be sure the flag is same in several GOP before saying it is open or closed).

For CLI, you can override default setting and use the one in MediaInfo CLI by adding " --ParseSpeed=0.5" to the command line.

We need to find how to have more coherency between the tools, as they currently have different default settings (different goals from different sponsors) because it is maybe not sustainable at long term to get such incoherencies due to theses different default settings.

**Comment by XMegamanX** [comment]
Hello !

Ok this is clearer now. This option has done the trick.

Thank you for the support \m/
