### ISSUE TITLE
All Occurrence TimeCode Track Check Not Working

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaConch_SourceCode#764]
I'm creating a test that checks to see if the timecode of our metadata is inside the timecode of the physical media file.

Generally, we define a rule to check all occurrences using "*" for TimeCode_FirstFrame, TimeCode_LastFrame and TimeCode_DropFrame.

```
<rule name="TimeCode_Start" value="TimeCode_FirstFrame" tracktype="Other" occurrence="*" operator="&lt;=">01:00:00;00</rule>
        <rule name="TimeCode_End" value="TimeCode_LastFrame" tracktype="Other" occurrence="*" operator="&gt;=">01:00:30;00</rule>
        <rule name="TimeCode_DropFrame" value="TimeCode_DropFrame" tracktype="Other" occurrence="*" operator="=">Yes</rule>
```

When there are multiple timecode tracks in a given file and one mismatches, the check  "*" does not work.

```
<track type="Other" typeorder="1">
<ID>1-Material</ID>
<Type>Time code</Type>
<Format>MXF TC</Format>
<FrameRate>29.970</FrameRate>
<FrameRate_Num>30000</FrameRate_Num>
<FrameRate_Den>1001</FrameRate_Den>
<FrameCount>960</FrameCount>
<TimeCode_FirstFrame>00:59:59;00</TimeCode_FirstFrame>
<TimeCode_LastFrame>01:00:30;29</TimeCode_LastFrame>
<TimeCode_Settings>Material Package</TimeCode_Settings>
<TimeCode_Stripped>Yes</TimeCode_Stripped>
</track>
<track type="Other" typeorder="2">
<ID>1-Source</ID>
<Type>Time code</Type>
<Format>MXF TC</Format>
<FrameRate>29.970</FrameRate>
<FrameRate_Num>30000</FrameRate_Num>
<FrameRate_Den>1001</FrameRate_Den>
<FrameCount>960</FrameCount>
<TimeCode_FirstFrame>00:59:59;00</TimeCode_FirstFrame>
<TimeCode_LastFrame>01:00:30;29</TimeCode_LastFrame>
<TimeCode_Settings>Source Package</TimeCode_Settings>
<TimeCode_Stripped>Yes</TimeCode_Stripped>
</track>
<track type="Other" typeorder="3">
<Type>Time code</Type>
<Format>SMPTE TC</Format>
<MuxingMode>SDTI</MuxingMode>
<FrameRate>30.000</FrameRate>
<FrameRate_Num>30</FrameRate_Num>
<FrameRate_Den>1</FrameRate_Den>
<TimeCode_FirstFrame>00:00:00:00</TimeCode_FirstFrame>
</track>
```
You'll see in the report, I ran a few tests.

1. Using the All occurrences "*" which reports pass despite occurrence 3 failing.
2. Using each of the 3 occurrences where you see occurrence 3 reports a failure while occurrences 1 and 2 pass as expected.

I'm seeing this on TimeCode_FirstFrame, TimeCode_LastFrame and TimeCode_DropFrame. In the case of track 3, it starts at a different timecode and doesn't have a last frame or a drop frame flag so i would expect them to fail with a "*" check.

[10042300.999 (1).mxf_MediaConchReport.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/12696276/10042300.999.1.mxf_MediaConchReport.txt)

[10042300.999_mxf_MediaInfo.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/12696266/10042300.999_mxf_MediaInfo.txt)

We can work around this by explicitly calling out the tracks and each occurrence instead of using "*" but wanted to get your thoughts on whether this is a bug and it should be reporting failed.

**Comment by JeromeMartinez** [comment]
"*" is synonym of "any", so if one track has the value it passes.
You can put "all" instead of "*" for checking all existing values.
Your 3rd track has no Time code of last frame because it is SDTI and we would have to seek to the end of the stream for getting its value (it may have discontinuities so it is not Time code of first frame + duration - 1), doable but not implemented, so a check on Time code of last frame would pass with your example as the 2 first tracks have the right value and the 3rd one has no value.
In theory, the Time code of last frame test could fail if you add another rule with "all" and "exists" but we see that we have a bug with it, we are working on fixing that. But in practice I don't recommend that for time codes, as presence of Time code of last frame depends on what we implemented.

We also see that the GUI was not modified and keep the legacy "*" instead of showing "any" and "all" options, we'll also change that.

**Comment by joe-sciame-wm** [comment]
Thanks Jerome! Yes, I had not seen the "any" and "all" changes. I really like that better as the language is clear.  Let me know once you have a version with these changes and we'll update our test plans.

**Comment by JeromeMartinez** [comment]
> Let me know once you have a version with these changes and we'll update our test plans.

It is already available with current versions, give it a try ;-).

The only issue is that "check if exists" does not work with "all" settings, so "all" settings is only for checking all streams values if they exist, but as said previously I don't think it is useful in your case.

```
<rule name="TimeCode_Start" value="TimeCode_FirstFrame" tracktype="Other" occurrence="all" operator="&lt;=">01:00:00;00</rule>
        <rule name="TimeCode_End" value="TimeCode_LastFrame" tracktype="Other" occurrence="all" operator="&gt;=">01:00:30;00</rule>
        <rule name="TimeCode_DropFrame" value="TimeCode_DropFrame" tracktype="Other" occurrence="all" operator="=">Yes</rule>
```
should do what you are looking for (error because track 3 "TimeCode_FirstFrame" is wrong).

> Did "\*" always mean any or did it used to mean "all"?

It means "any", hence the issue you have not catching track 3 not having the expected value (because tracks 1 & 2 have it, so at least one track have it, "any" is a pass, when "all" would be a fail).

**Comment by joe-sciame-wm** [comment]
Thanks Jerome!  I think the "all" for check if exists will be needed, but not in this particular scenario.

**Comment by g-maxime** [comment]
With the proposed changes, I think the following policy will works for your use case:
```
<policy type="and" name="TimeCode">
  <rule name="TimeCode_Start exists" value="TimeCode_FirstFrame" tracktype="Other" occurrence="all" operator="exists"/>
  <rule name="TimeCode_Start" value="TimeCode_FirstFrame" tracktype="Other" occurrence="all" operator="&lt;=">01:00:00;00</rule>
  <rule name="TimeCode_End exists" value="TimeCode_LastFrame" tracktype="Other" occurrence="all" operator="exists"/>
  <rule name="TimeCode_End" value="TimeCode_LastFrame" tracktype="Other" occurrence="all" operator="&gt;=">01:00:30;00</rule>
  <rule name="TimeCode_DropFrame exists" value="TimeCode_DropFrame" tracktype="Other" occurrence="all" operator="exists"/>
  <rule name="TimeCode_DropFrame" value="TimeCode_DropFrame" tracktype="Other" occurrence="all" operator="=">Yes</rule>
</policy>
```
For each field, the first rule checks if the field is present in all streams, and the second one checks if the existing fields matches the requested value.

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm [latest snapshots](https://mediaarea.net/download/snapshots/binary/) have the GUI more explicit ("any" and "all" rather that "\*")) and the "all" "exists" fix so all should be usable now.
